/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hsmui;

import hsmmodel.Hospital;
import hsmmodel.HospitalDirectory;
import javax.swing.JOptionPane;

/**
 *
 * @author prathamesh
 */
public class AddHospital extends javax.swing.JPanel {

    /**
     * Creates new form AddHospital
     */
    HospitalDirectory hospDirInfo;
    public AddHospital(HospitalDirectory hospDir) {
        initComponents();
        hospDirInfo = hospDir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtbx_name = new javax.swing.JTextField();
        txtbx_contact = new javax.swing.JTextField();
        NewEmployeeLabel = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();
        ResetButton = new javax.swing.JButton();
        PersonalInfoLabel1 = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        txtbx_city = new javax.swing.JComboBox<>();
        ContactLabel = new javax.swing.JLabel();
        txtbx_id = new javax.swing.JTextField();
        EmailLabel1 = new javax.swing.JLabel();
        GenderLabel1 = new javax.swing.JLabel();
        txtbx_community = new javax.swing.JComboBox<>();

        txtbx_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbx_nameKeyReleased(evt);
            }
        });

        txtbx_contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbx_contactKeyReleased(evt);
            }
        });

        NewEmployeeLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        NewEmployeeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewEmployeeLabel.setText("Add New Hospital");

        AddButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        AddButton.setText("ADD");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        NameLabel.setText("Name");

        ResetButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        PersonalInfoLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        PersonalInfoLabel1.setText("Conatct Information");

        GenderLabel.setText("City");

        txtbx_city.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select City", "Boston", "New York", "Seatle", "Washington DC", "LA", "Santa Barbara" }));
        txtbx_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbx_cityActionPerformed(evt);
            }
        });

        ContactLabel.setText("Contact");

        txtbx_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbx_idActionPerformed(evt);
            }
        });
        txtbx_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbx_idKeyReleased(evt);
            }
        });

        EmailLabel1.setText("Hospital ID");

        GenderLabel1.setText("Community");

        txtbx_community.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ", "Huntington", "Massachussets", "Kenmore", "Becon", "Park Drive", "Mission Hill", "Main", "Heath" }));
        txtbx_community.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbx_communityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(NewEmployeeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(326, 326, 326))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PersonalInfoLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(408, 408, 408))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(32, 32, 32))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(GenderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(43, 43, 43))
                                    .addComponent(GenderLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(EmailLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(2, 2, 2)))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtbx_id)
                                        .addGap(2, 2, 2))
                                    .addComponent(txtbx_name, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtbx_city, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtbx_community, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtbx_contact, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(301, 301, 301))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(NewEmployeeLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(EmailLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtbx_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(txtbx_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel)
                    .addComponent(txtbx_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel1)
                    .addComponent(txtbx_community, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PersonalInfoLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContactLabel)
                    .addComponent(txtbx_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(480, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtbx_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbx_nameKeyReleased
        // TODO add your handling code here:
//        String PATTERN = "^[A-Za-z\\\\s]+$";
//        Pattern pat = Pattern.compile(PATTERN);
//        Matcher match = pat.matcher(NameTxtBox.getText());
//        if(!match.matches() || NameTxtBox.getText().equals(""))
//        {
//            nLbl.setText("Name is incorrect!");
//        }
//        else
//        {
//            nLbl.setText("");
//        }

    }//GEN-LAST:event_txtbx_nameKeyReleased

    private void txtbx_contactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbx_contactKeyReleased
        // TODO add your handling code here:
//        String cellNo = ContactTxtBox.getText();
//
//        int length = cellNo.length();
//        char c = evt.getKeyChar();
//        if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' ){
//            if(length < 10)
//            {
//                ContactTxtBox.setEditable(true);
//            }
//            else
//            {
//                ContactLab.setText("Number is incorrect");
//                ContactTxtBox.setText("");
//
//            }
//        }
    }//GEN-LAST:event_txtbx_contactKeyReleased

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        
        
        
        String hsopId = txtbx_id.getText();
        String name = txtbx_name.getText();
        String city = txtbx_city.getSelectedItem().toString();
        String community = txtbx_community.getSelectedItem().toString();
        String contact = txtbx_contact.getText();
        
        Hospital hosp = hospDirInfo.addNewHospital();
        
        hosp.setHospitalID(hsopId);
        hosp.setName(name);
        hosp.setCity(city);
        hosp.setCommunity(community);


        JOptionPane.showMessageDialog(this , "New Hospital Information Added!");
        
        txtbx_id.setText("");
        txtbx_name.setText("");
        txtbx_contact.setText("");
        txtbx_city.setName("select gender");
        txtbx_community.setName("select");

        
    }//GEN-LAST:event_AddButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
        
        txtbx_id.setText("");
        txtbx_name.setText("");
        txtbx_contact.setText("");

        txtbx_city.setName("select gender");
        txtbx_community.setName("select");


    }//GEN-LAST:event_ResetButtonActionPerformed

    private void txtbx_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbx_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbx_idActionPerformed

    private void txtbx_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbx_idKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbx_idKeyReleased

    private void txtbx_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbx_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbx_cityActionPerformed

    private void txtbx_communityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbx_communityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbx_communityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel ContactLabel;
    private javax.swing.JLabel EmailLabel1;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel GenderLabel1;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel NewEmployeeLabel;
    private javax.swing.JLabel PersonalInfoLabel1;
    private javax.swing.JButton ResetButton;
    private javax.swing.JComboBox<String> txtbx_city;
    private javax.swing.JComboBox<String> txtbx_community;
    private javax.swing.JTextField txtbx_contact;
    private javax.swing.JTextField txtbx_id;
    private javax.swing.JTextField txtbx_name;
    // End of variables declaration//GEN-END:variables
}
