/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hsmui;

import hsmmodel.Doctor;
import hsmmodel.Patient;
import hsmmodel.PatientDirectory;
import javax.swing.JOptionPane;

/**
 *
 * @author prathamesh
 */
public class AddPatient extends javax.swing.JPanel {

    /**
     * Creates new form AddPatient
     */
    
    PatientDirectory ptnDir;
    public AddPatient(PatientDirectory ptnDir) {
        initComponents();
        this.ptnDir = ptnDir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddButton = new javax.swing.JButton();
        GenderLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        ResetButton = new javax.swing.JButton();
        txtbx_gender = new javax.swing.JComboBox<>();
        PersonalInfoLabel1 = new javax.swing.JLabel();
        txtbx_name = new javax.swing.JTextField();
        txtbx_age = new javax.swing.JTextField();
        txtbx_id = new javax.swing.JTextField();
        txtbx_contact = new javax.swing.JTextField();
        EmailLabel1 = new javax.swing.JLabel();
        ContactLabel = new javax.swing.JLabel();
        txtbx_email = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        NewEmployeeLabel = new javax.swing.JLabel();
        AgeLabel1 = new javax.swing.JLabel();
        txtbx_height = new javax.swing.JTextField();
        AgeLabel2 = new javax.swing.JLabel();
        txtbx_weight = new javax.swing.JTextField();
        AgeLabel3 = new javax.swing.JLabel();
        txtbx_bloodgroup = new javax.swing.JTextField();

        AddButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        AddButton.setText("ADD");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        GenderLabel.setText("Gender");

        NameLabel.setText("Name");

        AgeLabel.setText("Age");

        ResetButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        txtbx_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select gender...", "Male", "Female", "Other" }));

        PersonalInfoLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        PersonalInfoLabel1.setText("Conatct Information");

        txtbx_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbx_nameKeyReleased(evt);
            }
        });

        txtbx_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbx_idActionPerformed(evt);
            }
        });
        txtbx_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbx_idKeyReleased(evt);
            }
        });

        txtbx_contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbx_contactKeyReleased(evt);
            }
        });

        EmailLabel1.setText("Patient ID");

        ContactLabel.setText("Contact");

        txtbx_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbx_emailActionPerformed(evt);
            }
        });
        txtbx_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbx_emailKeyReleased(evt);
            }
        });

        EmailLabel.setText("Email Id");

        NewEmployeeLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        NewEmployeeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewEmployeeLabel.setText("Add New Patient");

        AgeLabel1.setText("Height");

        AgeLabel2.setText("Weight");

        AgeLabel3.setText("Blood Group");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(NewEmployeeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ContactLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(239, 239, 239))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PersonalInfoLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(ResetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbx_email)
                            .addComponent(txtbx_contact)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(40, 40, 40))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(GenderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(31, 31, 31))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AgeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(52, 52, 52))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AgeLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(37, 37, 37))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AgeLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(34, 34, 34))
                                    .addComponent(AgeLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(83, 83, 83))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EmailLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(70, 70, 70)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbx_id)
                            .addComponent(txtbx_name, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtbx_gender, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtbx_age, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtbx_height, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtbx_weight, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtbx_bloodgroup, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(306, 306, 306))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(NewEmployeeLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbx_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLabel1))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(txtbx_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel)
                    .addComponent(txtbx_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel)
                    .addComponent(txtbx_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel1)
                    .addComponent(txtbx_height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel2)
                    .addComponent(txtbx_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel3)
                    .addComponent(txtbx_bloodgroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(PersonalInfoLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContactLabel)
                    .addComponent(txtbx_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtbx_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(356, 356, 356))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        
        Patient ptn = ptnDir.addNewPatient();
        
        String ptnId = txtbx_id.getText();
        String name = txtbx_name.getText();
        String gender = txtbx_gender.getSelectedItem().toString();
        String age = txtbx_age.getText();
        String contact = txtbx_contact.getText();
        String email = txtbx_email.getText();
        String height = txtbx_height.getText();
        String weight = txtbx_weight.getText();
        String bgroup = txtbx_bloodgroup.getText();
        
        ptn.setPatiendId(ptnId);
        ptn.setName(name);
        ptn.setGender(gender);
        ptn.setAge(age);
        ptn.setContact(contact);
        ptn.setEmail(email);
        ptn.setHeight(height);
        ptn.setWeight(weight);
        ptn.setBloodGroup(bgroup);

        JOptionPane.showMessageDialog(this , "New Patient Information Added!");
        
        txtbx_id.setText("");
        txtbx_name.setText("");
        txtbx_age.setText("");
        txtbx_contact.setText("");
        txtbx_email.setText("");
        txtbx_gender.setName("select gender");
        txtbx_height.setText("");
        txtbx_weight.setText("");
        txtbx_bloodgroup.setText("");
        
    }//GEN-LAST:event_AddButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
        txtbx_id.setText("");
        txtbx_name.setText("");
        txtbx_age.setText("");
        txtbx_contact.setText("");
        txtbx_email.setText("");
        txtbx_gender.setName("select gender");
        txtbx_height.setText("");
        txtbx_weight.setText("");
        txtbx_bloodgroup.setText("");
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void txtbx_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbx_nameKeyReleased
        // TODO add your handling code here:
        //        String PATTERN = "^[A-Za-z\\\\s]+$";
        //        Pattern pat = Pattern.compile(PATTERN);
        //        Matcher match = pat.matcher(NameTxtBox.getText());
        //        if(!match.matches() || NameTxtBox.getText().equals(""))
        //        {
            //            nLbl.setText("Name is incorrect!");
            //        }
        //        else
        //        {
            //            nLbl.setText("");
            //        }
    }//GEN-LAST:event_txtbx_nameKeyReleased

    private void txtbx_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbx_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbx_idActionPerformed

    private void txtbx_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbx_idKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbx_idKeyReleased

    private void txtbx_contactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbx_contactKeyReleased
        // TODO add your handling code here:
        //        String cellNo = ContactTxtBox.getText();
        //
        //        int length = cellNo.length();
        //        char c = evt.getKeyChar();
        //        if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' ){
            //            if(length < 10)
            //            {
                //                ContactTxtBox.setEditable(true);
                //            }
            //            else
            //            {
                //                ContactLab.setText("Number is incorrect");
                //                ContactTxtBox.setText("");
                //
                //            }
            //        }
    }//GEN-LAST:event_txtbx_contactKeyReleased

    private void txtbx_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbx_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbx_emailActionPerformed

    private void txtbx_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbx_emailKeyReleased
        // TODO add your handling code here:
        //        String PATTERN = "^[a-zA-Z0-9] (0,30)[@] [a-zA-Z0-9] (0,10) [.] [a-zA-Z] (0,5)$";
        //        Pattern pat = Pattern.compile(PATTERN);
        //        Matcher match = pat.matcher(EmailTxtBox.getText());
        //        if(!match.matches() || EmailTxtBox.getText().equals(""))
        //            emLab.setText("Email is incorrect");
        //        else if(match.matches())
        //            emLab.setText("");
        //        else
        //            emLab.setText("Email Format is ");
    }//GEN-LAST:event_txtbx_emailKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JLabel AgeLabel1;
    private javax.swing.JLabel AgeLabel2;
    private javax.swing.JLabel AgeLabel3;
    private javax.swing.JLabel ContactLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel EmailLabel1;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel NewEmployeeLabel;
    private javax.swing.JLabel PersonalInfoLabel1;
    private javax.swing.JButton ResetButton;
    private javax.swing.JTextField txtbx_age;
    private javax.swing.JTextField txtbx_bloodgroup;
    private javax.swing.JTextField txtbx_contact;
    private javax.swing.JTextField txtbx_email;
    private javax.swing.JComboBox<String> txtbx_gender;
    private javax.swing.JTextField txtbx_height;
    private javax.swing.JTextField txtbx_id;
    private javax.swing.JTextField txtbx_name;
    private javax.swing.JTextField txtbx_weight;
    // End of variables declaration//GEN-END:variables
}
