/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hsmui;

import hsmmodel.Patient;
import hsmmodel.PatientCatalogue;

/**
 *
 * @author vivekhanagoji
 */
public class PatientAddJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientAddJPanel
     */
    PatientCatalogue patient;
    public PatientAddJPanel(PatientCatalogue patient) {
        initComponents();
        
        this.patient = patient;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHospitalID = new javax.swing.JTextField();
        PersonalInfoLabel1 = new javax.swing.JLabel();
        txtEmailID = new javax.swing.JTextField();
        GenderLabel = new javax.swing.JLabel();
        ContactLabel = new javax.swing.JLabel();
        txtPatID = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        txtPatName = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        txtHospitalName = new javax.swing.JTextField();
        HospitalNamelbl = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create New Patient");

        jLabel2.setText("Age");

        jLabel6.setText("Hospital ID");

        PersonalInfoLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        PersonalInfoLabel1.setText("Contact Information");

        txtEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIDActionPerformed(evt);
            }
        });

        GenderLabel.setText("Gender");

        ContactLabel.setText("Contact");

        EmailLabel.setText("Email Id");

        AddButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        AddButton.setText("ADD");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Pateint Name");

        HospitalNamelbl.setText("Hospital Name");

        NameLabel.setText("Patient ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameLabel)
                    .addComponent(jLabel4)
                    .addComponent(GenderLabel)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(HospitalNamelbl)
                    .addComponent(ContactLabel)
                    .addComponent(EmailLabel))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtPatID)
                        .addComponent(txtGender)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPatName)
                        .addComponent(txtHospitalID, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PersonalInfoLabel1)
                .addGap(325, 325, 325))
            .addGroup(layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(txtPatID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHospitalID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HospitalNamelbl)
                    .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(PersonalInfoLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContactLabel)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIDActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        Patient pat = patient.addNewPateint();
        //        String docName = txtDocName.getText();
        //        String docID = txtDocID.getText();
        //        String gender = txtGender.getText();
        //        String age = txtAge.getText();
        //        String Designation = txtDesignation.getText();
        //        String Specialization = txtSpecialization.getText();
//        //        String PhoneNo = txtContact.getText();
//        //        String Emailid =txtEmailID.getText();
//
//        pat.setPateintName(txtPatName.getText());
//        pat.setPateintID(Integer.parseInt(txtPatID.getText()));
//        pat.setGender(txtGender.getText());
//        pat.setAge(Integer.parseInt(txtAge.getText()));
//        pat.setHospitalName(txtHospitalName.getText());
//        pat.setHospitalID(Integer.parseInt(txtHospitalID.getText()));
//        pat.setContactNum(txtContact.getText());
//        pat.setEmailID(txtEmailID.getText());
//
//        JOptionPane.showMessageDialog(this, "New Doctor Created");
//
//        txtPatName.setText("");
//        txtPatID.setText("");
//        txtGender.setText("");
//        txtHospitalID.setText("");
//        txtPatName.setText("");
//        txtAge.setText("");
//        txtDesignation.setText("");
//        txtSpecialization.setText("");
//        txtContact.setText("");
//        txtEmailID.setText("");

        //
        //        doc.setDocID(docId);
        //        doc.setDocName(name);
        //        doc.setGender(gender);
        //
        //        JOptionPane.showMessageDialog(this , "New Doctor Information Added!");
        //
        //        txt_id.setText("");
        //        txtname.setText("");
        //        txtage.setText("");
        //        txtcontact.setText("");
        //        txtemail.setText("");
        //        txtgender.setName("select gender");

        //        Employee emp = employeedir.addNewEmployee();
        //        String Name = NameTxtBox.getText();
        //        String Gender = GenderTxtBox.getSelectedItem().toString();
        //        int Age = Integer.parseInt(AgeTxtBox.getText());
        //        String EmpID = EmpIdTxtBox.getText();
        //        String Team = TeamTxtBox.getText();
        //        String Position = PositionTxtBox.getText();
        //        String Level = LevelTxtBox.getText();
        //        String Contact = ContactTxtBox.getText();
        //        String Email = EmailTxtBox.getText();
        //        String Date = DateTxtBox.getText();
        //        String Path = filepath;
        //
        //        emp.setEmployeeID(EmpID);
        //        emp.setName(Name);
        //        emp.setGender(Gender);
        //        emp.setAge(Age);
        //        emp.setTeamInfo(Team);
        //        emp.setPositionTitle(Position);
        //        emp.setLevel(Level);
        //        emp.setContact(Contact);
        //        emp.setEmail(Email);
        //        emp.setStartDate(Date);
        //        emp.setImage(Path);
        //
        //        JOptionPane.showMessageDialog(this , "New Employee Information Added!");
        //
        //        NameTxtBox.setText("");
        //        GenderTxtBox.setName("select");
        //        AgeTxtBox.setText("");
        //        EmpIdTxtBox.setText("");
        //        TeamTxtBox.setText("");
        //        PositionTxtBox.setText("");
        //        LevelTxtBox.setText("");
        //        ContactTxtBox.setText("");
        //        EmailTxtBox.setText("");
        //        DateTxtBox.setText("");
        //        ImageLabel.setText("");
        //        nLbl.setText("");
    }//GEN-LAST:event_AddButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel ContactLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel HospitalNamelbl;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel PersonalInfoLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtHospitalID;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JTextField txtPatID;
    private javax.swing.JTextField txtPatName;
    // End of variables declaration//GEN-END:variables
}
