/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hsmui;

import hsmmodel.Encounter;
import hsmmodel.Person;
import hsmmodel.PersonCatalogue;
import hsmmodel.Vital;
import hsmmodel.VitalHistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vivekhanagoji
 */
public class PersonAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonAdminJPanel
     */
    PersonCatalogue person;
    VitalHistory vitalHistory;
    Encounter encounter;
    public PersonAdminJPanel(PersonCatalogue person) {
        initComponents();
        this.person = person;
        populatePatientTable();
        this.encounter = encounter;
        vitalHistory = new VitalHistory();
    }
    
        private void populatePatientTable() {
        DefaultTableModel model = (DefaultTableModel) tblPatientTable.getModel();
       model.setRowCount(0);
       
       for (Person pa : person.getPerson()){
           Object[] row = new Object[7];
           row[0] = pa;
           row[1] = pa.getAge();
           row[2] = pa.getEmailID();
          // row[3] = pa.getAge(); //add Community here
          // row[4] = pa.getCommunity();
           //row[6] = pa.getDoctorName();
           model.addRow(row);
           
       }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatientTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        VitalJPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lablId = new javax.swing.JLabel();
        textPatientName = new javax.swing.JTextField();
        labelBloodSugar = new javax.swing.JLabel();
        txtBloodSugar = new javax.swing.JTextField();
        labelPressure = new javax.swing.JLabel();
        txtBloodPressure = new javax.swing.JTextField();
        labelTemperature = new javax.swing.JLabel();
        txtBodyTemp = new javax.swing.JTextField();
        labelPulse = new javax.swing.JLabel();
        txtPulseRate = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        labelPulse1 = new javax.swing.JLabel();
        txtDoctorName = new javax.swing.JTextField();
        lablId1 = new javax.swing.JLabel();
        txtPID = new javax.swing.JTextField();
        btnAddPatient = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEncounter = new javax.swing.JTable();
        btnAddDctor = new javax.swing.JButton();

        tblPatientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Person Name", "Person Age", "Email ID"
            }
        ));
        tblPatientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPatientTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPatientTable);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Person");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Vital Signs");

        lablId.setText("Patient Name");

        labelBloodSugar.setText("Blood Sugar");

        labelPressure.setText("Blood Pressure");

        txtBloodPressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodPressureActionPerformed(evt);
            }
        });

        labelTemperature.setText("Body Temperature");

        labelPulse.setText("Pulse Rate");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        labelPulse1.setText("Doctor Name");

        lablId1.setText("Patient ID");

        javax.swing.GroupLayout VitalJPanelLayout = new javax.swing.GroupLayout(VitalJPanel);
        VitalJPanel.setLayout(VitalJPanelLayout);
        VitalJPanelLayout.setHorizontalGroup(
            VitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VitalJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(VitalJPanelLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(btnSave)
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(VitalJPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(VitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VitalJPanelLayout.createSequentialGroup()
                        .addComponent(lablId1)
                        .addGap(58, 58, 58)
                        .addComponent(txtPID))
                    .addGroup(VitalJPanelLayout.createSequentialGroup()
                        .addComponent(labelPulse1)
                        .addGap(38, 38, 38)
                        .addComponent(txtDoctorName))
                    .addGroup(VitalJPanelLayout.createSequentialGroup()
                        .addComponent(labelPulse)
                        .addGap(51, 51, 51)
                        .addComponent(txtPulseRate))
                    .addGroup(VitalJPanelLayout.createSequentialGroup()
                        .addComponent(labelTemperature)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBodyTemp))
                    .addGroup(VitalJPanelLayout.createSequentialGroup()
                        .addComponent(labelPressure)
                        .addGap(25, 25, 25)
                        .addComponent(txtBloodPressure))
                    .addGroup(VitalJPanelLayout.createSequentialGroup()
                        .addComponent(labelBloodSugar)
                        .addGap(43, 43, 43)
                        .addComponent(txtBloodSugar))
                    .addGroup(VitalJPanelLayout.createSequentialGroup()
                        .addComponent(lablId)
                        .addGap(36, 36, 36)
                        .addComponent(textPatientName)))
                .addGap(42, 42, 42))
        );
        VitalJPanelLayout.setVerticalGroup(
            VitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VitalJPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGroup(VitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VitalJPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lablId1)
                        .addGap(18, 18, 18)
                        .addComponent(lablId)
                        .addGap(18, 18, 18)
                        .addComponent(labelBloodSugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(VitalJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBloodSugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(VitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelPressure)
                    .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTemperature)
                    .addComponent(txtBodyTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(VitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelPulse)
                    .addComponent(txtPulseRate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VitalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPulse1)
                    .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(btnSave)
                .addContainerGap())
        );

        btnAddPatient.setText("Add as a Patient");
        btnAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPatientActionPerformed(evt);
            }
        });

        tableEncounter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Patient Name", "Blood Sugar", "Blood Pressure", "Body Temperature", "Pulse Rate", "Doctor Name", "Encounter"
            }
        ));
        jScrollPane2.setViewportView(tableEncounter);

        btnAddDctor.setText("Add as a Doctor");
        btnAddDctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDctorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(btnAddPatient)
                        .addGap(45, 45, 45)
                        .addComponent(btnAddDctor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(VitalJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPatient)
                    .addComponent(btnAddDctor))
                .addGap(18, 18, 18)
                .addComponent(VitalJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblPatientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPatientTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPatientTableMouseClicked

    private void btnAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPatientActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblPatientTable.getModel();
        int selectedRowIndex = tblPatientTable.getSelectedRow();
        
        
         if (selectedRowIndex < 0) {
            JOptionPane.showConfirmDialog(this, "Please select a row");
            return;
        }

         Person selectedPerson =(Person) model.getValueAt(selectedRowIndex, 0);
       
         textPatientName.setText(selectedPerson.getName());
    }//GEN-LAST:event_btnAddPatientActionPerformed

    private void txtBloodPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodPressureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodPressureActionPerformed

    private void btnAddDctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDctorActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tblPatientTable.getModel();
        int selectedRowIndex = tblPatientTable.getSelectedRow();
        
        
         if (selectedRowIndex < 0) {
            JOptionPane.showConfirmDialog(this, "Please select a row");
            return;
        }

         Person selectedPerson =(Person) model.getValueAt(selectedRowIndex, 0);
       
         txtDoctorName.setText(selectedPerson.getName());
    }//GEN-LAST:event_btnAddDctorActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
      //  int selectedRowIndex = tableEncounter.getSelectedRow();

        DefaultTableModel model = (DefaultTableModel) tblPatientTable.getModel();
        int selectedRowIndex = tblPatientTable.getSelectedRow();
        
                if(selectedRowIndex <0)
        {
            JOptionPane.showMessageDialog(this,"Please select a row to view employee details");
           return;
        }
    //  Encounter enc = (Encounter) model.getValueAt(selectedRowIndex, 0);
    Encounter e = new Encounter();
      Vital v = vitalHistory.addVitals();
      v.setBloodPressure(Integer.parseInt(txtBloodPressure.getText()));
                v.setPulseRate(Integer.parseInt(txtPulseRate.getText()));
                v.setBodyTemp(Integer.parseInt(txtBodyTemp.getText()));
                v.setBloodSugar(Integer.parseInt(txtBloodSugar.getText()));
                e.setEncounterCount(e.getEncounterCount()+1);
                v.setEncounter(e);
                JOptionPane.showMessageDialog(this, "Vitals for selected patient added");
                
                populateEncounterTable();
      
      
      
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel VitalJPanel;
    private javax.swing.JButton btnAddDctor;
    private javax.swing.JButton btnAddPatient;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelBloodSugar;
    private javax.swing.JLabel labelPressure;
    private javax.swing.JLabel labelPulse;
    private javax.swing.JLabel labelPulse1;
    private javax.swing.JLabel labelTemperature;
    private javax.swing.JLabel lablId;
    private javax.swing.JLabel lablId1;
    private javax.swing.JTable tableEncounter;
    private javax.swing.JTable tblPatientTable;
    private javax.swing.JTextField textPatientName;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtBloodSugar;
    private javax.swing.JTextField txtBodyTemp;
    private javax.swing.JTextField txtDoctorName;
    private javax.swing.JTextField txtPID;
    private javax.swing.JTextField txtPulseRate;
    // End of variables declaration//GEN-END:variables

    private void populateEncounterTable() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
     DefaultTableModel model = (DefaultTableModel) tableEncounter.getModel();
       model.setRowCount(0);
       
       for (Vital v : vitalHistory.getVitalsHistory()){
           Object[] row = new Object[6];
           row[0] = v.getBloodSugar();
           row[1] = v.getBloodPressure();
           row[2] = v.getBodyTemp();
           row[3] = v.getPulseRate();
           row[4] = v.getEncounter().getEncounterCount();
           model.addRow(row);
       }
    
    }
}
