/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hsmui;

import javax.swing.JOptionPane;

/**
 *
 * @author prathamesh
 */
public class StartJFrame extends javax.swing.JFrame {

    /**
     * Creates new form StartJFrame
     */
    public StartJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        txtbx_loginas = new javax.swing.JComboBox<>();
        AgeLabel = new javax.swing.JLabel();
        txtbx_us = new javax.swing.JTextField();
        ContactLabel = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        pwd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Welcome to Hospital Management System");

        GenderLabel.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        GenderLabel.setText("Login as");

        txtbx_loginas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select..", "System Admin", "Community Admin", "Hospital Admin", "Patient", "Doctor ", " " }));

        AgeLabel.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        AgeLabel.setText("Username");

        ContactLabel.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        ContactLabel.setText("Password");

        AddButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        AddButton.setText("Login");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        pwd.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AgeLabel)
                                    .addComponent(ContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(GenderLabel)
                                .addGap(21, 21, 21)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtbx_loginas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtbx_us)
                                    .addComponent(pwd, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))))))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbx_loginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenderLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbx_us, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContactLabel)
                    .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(490, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        String loginas = txtbx_loginas.getSelectedItem().toString();
        
        if(txtbx_us.getText().equals("admin") && pwd.getText().equals("admin"))
        {
            JOptionPane.showMessageDialog(this,"Login Successful, Welcome");
            this.dispose();
            HMO_MainFrame main = new HMO_MainFrame(loginas);
            main.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Invalid Credentials");
        }
        
//        Person prsn = prnDir.addNewPerson();
//
//        String Name = txtbx_prname.getText();
//        String Gender = txtbx_gender.getSelectedItem().toString();
//        String city = txtbx_city.getSelectedItem().toString();
//        String community = txtbx_com.getSelectedItem().toString();
//        String Age = txtbx_prage.getText();
//        String PersonID = txtbx_prid.getText();
//        String Contact = txtbx_contact.getText();
//        String personType = txtbx_persontype.getSelectedItem().toString();
//
//        if(personType == "Patient"){
//            Patient ptn = ptnDir.addNewPatient();
//
//            ptn.setPatiendId(PersonID);
//            ptn.setName(Name);
//            ptn.setGender(Gender);
//            ptn.setAge(Age);
//            ptn.setContact(Contact);
//
//            JOptionPane.showMessageDialog(this , "Added Person as Patient!");
//        }else if(personType == "Doctor"){
//            Doctor doc = docDir.addNewDoctor();
//
//            doc.setDocID(PersonID);
//            doc.setDocName(Name);
//            doc.setGender(Gender);
//            doc.setAge(Age);
//            doc.setContact(Contact);
//
//            JOptionPane.showMessageDialog(this , "Added as Person as Doctor!");
//        }else{
//            prsn.setName(Name);
//            prsn.setPersonID(PersonID);
//            prsn.setGender(Gender);
//            prsn.setAge(Age);
//            prsn.setContact(Contact);
//            prsn.setCommunity(community);
//            prsn.setCity(city);
//
//            JOptionPane.showMessageDialog(this , "New Person Added!");
//
//        }
//
//        txtbx_prid.setText("");
//        txtbx_prname.setText("");
//        txtbx_prage.setText("");
//        txtbx_contact.setText("");
//        txtbx_gender.setName("select");
//        txtbx_com.setName("select");
//        txtbx_city.setName("select");

        //                prsn.setName(Name);
        //                prsn.setPersonID(PersonID);
        //                prsn.setGender(Gender);
        //                prsn.setAge(Age);
        //                prsn.setContact(Contact);
        //                prsn.setCommunity(community);
        //                prsn.setCity(city);
        //
        //
        //                JOptionPane.showMessageDialog(this , "New Person Added!");
        //
        //                txtbx_prid.setText("");
        //                txtbx_prname.setText("");
        //                txtbx_prage.setText("");
        //                txtbx_contact.setText("");
        //                txtbx_gender.setName("select");
        //                txtbx_com.setName("select");
        //                txtbx_city.setName("select");

        //
        //        emp.setEmployeeID(EmpID);
        //        emp.setName(Name);
        //        emp.setGender(Gender);
        //        emp.setAge(Age);
        //        emp.setTeamInfo(Team);
        //        emp.setPositionTitle(Position);
        //        emp.setLevel(Level);
        //        emp.setContact(Contact);
        //        emp.setEmail(Email);
        //        emp.setStartDate(Date);
        //        emp.setImage(Path);
        //
        //        JOptionPane.showMessageDialog(this , "New Employee Information Added!");
        //
        //        NameTxtBox.setText("");
        //        GenderTxtBox.setName("select");
        //        AgeTxtBox.setText("");
        //        EmpIdTxtBox.setText("");
        //        TeamTxtBox.setText("");
        //        PositionTxtBox.setText("");
        //        LevelTxtBox.setText("");
        //        ContactTxtBox.setText("");
        //        EmailTxtBox.setText("");
        //        DateTxtBox.setText("");
        //        ImageLabel.setText("");
        //        nLbl.setText("");
    }//GEN-LAST:event_AddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JLabel ContactLabel;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JComboBox<String> txtbx_loginas;
    private javax.swing.JTextField txtbx_us;
    // End of variables declaration//GEN-END:variables
}
