/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Patient;
import Model.PatientDirectory;
import Model3.Community;
import Model3.CommunityHistory;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vivek
 */
public class AdminPatient extends javax.swing.JPanel {

    /**
     * Creates new form AdminPatient
     */
    
    private ArrayList<Community> cList = new ArrayList<>();
//
    private HashSet<String> cityList = new HashSet<>();
    
    private HashMap<String, ArrayList<String>> map = new HashMap<>();
    
    PatientDirectory ptnDir;
    CommunityHistory comm;
    
    public AdminPatient(PatientDirectory ptnDir, CommunityHistory comm) {
        initComponents();
        this.ptnDir = ptnDir;
        this.comm = comm;
        
        populateTable();
    }
    
    private void populateTable(){
        
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        model.setRowCount(0);
        
        for(Patient ptn : ptnDir.getPatientDirectory()){
            
            Object[] row = new Object[4];
            row[0] = ptn;
            row[1] = ptn.getName();
            row[2] = ptn.getAge();
            row[3] = ptn.getGender();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtbx_gender = new javax.swing.JTextField();
        NameLabel1 = new javax.swing.JLabel();
        txtbx_name = new javax.swing.JTextField();
        btn_view = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        EmailLabel = new javax.swing.JLabel();
        ContactLabel = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        PersonalInfoLabel = new javax.swing.JLabel();
        txtbx_age = new javax.swing.JTextField();
        GenderLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        txtbx_contact = new javax.swing.JTextField();
        txtbx_id = new javax.swing.JTextField();
        NewEmployeeLabel = new javax.swing.JLabel();
        PersonalInfoLabel1 = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        txtbx_email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        AgeLabel1 = new javax.swing.JLabel();
        txtbx_height = new javax.swing.JTextField();
        txtbx_weight = new javax.swing.JTextField();
        AgeLabel2 = new javax.swing.JLabel();
        AgeLabel3 = new javax.swing.JLabel();
        txtbx_bloodgroup = new javax.swing.JTextField();
        SearchTxtBox = new javax.swing.JTextField();
        btnSearch1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        AgeLabel4 = new javax.swing.JLabel();
        AgeLabel5 = new javax.swing.JLabel();
        AdminPatDirCityCombo = new javax.swing.JComboBox<>();
        AdminPatDirCommCombo = new javax.swing.JComboBox<>();

        NameLabel1.setText("Name");

        btn_view.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_view.setText("View");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        EmailLabel.setText("Email Id");

        ContactLabel.setText("Contact");

        btn_add.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_add.setText("Delete");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        PersonalInfoLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        PersonalInfoLabel.setText("Personal Details");

        GenderLabel.setText("Gender");

        NameLabel.setText("Patient ID");

        NewEmployeeLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        NewEmployeeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewEmployeeLabel.setText("Patient Directory");

        PersonalInfoLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        PersonalInfoLabel1.setText("Conatct Information");

        AgeLabel.setText("Age");

        txtbx_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbx_emailActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient ID", "Name", "Age", "Gender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table);

        AgeLabel1.setText("Height");

        AgeLabel2.setText("Weight");

        AgeLabel3.setText("Blood Group");

        SearchTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTxtBoxActionPerformed(evt);
            }
        });

        btnSearch1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnSearch1.setText("Search");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel19.setText("Patient ID:");

        AgeLabel4.setText("City");

        AgeLabel5.setText("Community");

        AdminPatDirCityCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminPatDirCityComboActionPerformed(evt);
            }
        });

        AdminPatDirCommCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminPatDirCommComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(txtbx_email))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(txtbx_contact))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(GenderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(31, 31, 31))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AgeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(52, 52, 52))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(40, 40, 40))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AgeLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(37, 37, 37))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AgeLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(34, 34, 34))
                                    .addComponent(AgeLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AgeLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(52, 52, 52))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AgeLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(52, 52, 52)))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtbx_id)
                                    .addComponent(txtbx_gender)
                                    .addComponent(txtbx_age)
                                    .addComponent(txtbx_name)
                                    .addComponent(txtbx_height)
                                    .addComponent(txtbx_weight)
                                    .addComponent(txtbx_bloodgroup)
                                    .addComponent(AdminPatDirCityCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AdminPatDirCommCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(PersonalInfoLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(49, 49, 49))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(EmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(148, 148, 148))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ContactLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(150, 150, 150)))
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PersonalInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(124, 124, 124)))))
                .addGap(589, 589, 589))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(553, 553, 553)
                .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(693, 693, 693)
                        .addComponent(btn_view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel19)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SearchTxtBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NewEmployeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(354, 354, 354))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewEmployeeLabel)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SearchTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_view)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PersonalInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(txtbx_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel1)
                    .addComponent(txtbx_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel)
                    .addComponent(txtbx_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel)
                    .addComponent(txtbx_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel4)
                    .addComponent(AdminPatDirCityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel5)
                    .addComponent(AdminPatDirCommCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel1)
                    .addComponent(txtbx_height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel2)
                    .addComponent(txtbx_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel3)
                    .addComponent(txtbx_bloodgroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(PersonalInfoLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContactLabel)
                    .addComponent(txtbx_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbx_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_update)
                    .addComponent(btn_add))
                .addContainerGap(90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        // TODO add your handling code here:

        int row = Table.getSelectedRow();

        if(row<0){
            JOptionPane.showMessageDialog(this, "Please select a ROW to search ");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        Patient selectedPatient = (Patient)model.getValueAt(row, 0);

        String selectedCity = selectedPatient.getPatientCity();
        String selectedComm = selectedPatient.getPatientCommunity();

        txtbx_id.setText(selectedPatient.getPatiendId());
        txtbx_name.setText(selectedPatient.getName());
        txtbx_email.setText(selectedPatient.getEmail());
        txtbx_contact.setText(selectedPatient.getContact());
        txtbx_gender.setText(selectedPatient.getGender());
        txtbx_age.setText(selectedPatient.getAge());
        txtbx_height.setText(selectedPatient.getHeight());
        txtbx_weight.setText(selectedPatient.getWeight());
        txtbx_bloodgroup.setText(selectedPatient.getBloodGroup());
        AdminPatDirCityCombo.setSelectedItem(selectedPatient.getPatientCity());
        AdminPatDirCommCombo.setSelectedItem(selectedPatient.getPatientCommunity());

        AdminPatDirCommCombo.addItem(selectedComm);
        AdminPatDirCityCombo.addItem(selectedCity);
//        for (String city : cityList) {
//            HospUpdateCityCombo.addItem(city);
//            
//        }
//        AdminPatDirCityCombo.setSelectedItem(selectedPatient.getPatientCity());
//        AdminPatDirCommCombo.setSelectedItem(selectedPatient.getPatientCommunity());

        cList = comm.getCommunityDetails();
        for (Community community : cList) {

            cityList.add(community.getCity());
            //cityList.remove(selectedCity);
            //communityNameList.add(community.getCommunity());
//            houseList.add(community.getHouse().getAddress());
        }

//        HospCityCombobox.addItem("Select a city");
        for (String city : cityList) {

            if (city == selectedCity) {
                AdminPatDirCityCombo.insertItemAt(city, 0);
            } else {
                AdminPatDirCityCombo.addItem(city);
            }

        }
        setCommunityAllProperties();
    }//GEN-LAST:event_btn_viewActionPerformed

    private void setCommunityAllProperties() {

        for (Community community : cList) {

            ArrayList<String> communityVal = new ArrayList<>();

            if (cityList.contains(community.getCity())) {
                if (map.get(community.getCity()) == null) {
                    communityVal.add(community.getCommunity());
                    map.put(community.getCity(), communityVal);
                } else {

                    map.get(community.getCity()).add(community.getCommunity());

                }

            }

        }

    }
    
    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        int row = Table.getSelectedRow();

        if(row<0){
            JOptionPane.showMessageDialog(this, "Please select a ROW to search ");
            return;
        }
//
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        Patient selectedPatient = (Patient)model.getValueAt(row, 0);
        
        String id = txtbx_id.getText();
        String name = txtbx_name.getText();
        String email = txtbx_email.getText();
        String contact = txtbx_contact.getText();
        String gender = txtbx_gender.getText();
        String age = txtbx_age.getText();
        String height = txtbx_height.getText();
        String weight = txtbx_weight.getText();
        String bloodgroup = txtbx_bloodgroup.getText();
        String PatCity = AdminPatDirCityCombo.getSelectedItem().toString();
        String PatComm = AdminPatDirCommCombo.getSelectedItem().toString();
        
        
        selectedPatient.setPatiendId(id);
        selectedPatient.setName(name);
        selectedPatient.setContact(contact);
        selectedPatient.setEmail(email);
        selectedPatient.setGender(gender);
        selectedPatient.setAge(age);
        selectedPatient.setHeight(height);
        selectedPatient.setWeight(weight);
        selectedPatient.setBloodGroup(bloodgroup);
        selectedPatient.setPatientCity(PatCity);
        selectedPatient.setPatientCommunity(PatComm);
        
        JOptionPane.showMessageDialog(this, "Hospital Information Updated");
        
        populateTable();
        
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addActionPerformed

    private void txtbx_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbx_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbx_emailActionPerformed

    private void SearchTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTxtBoxActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        // TODO add your handling code here:
        String search = SearchTxtBox.getText();
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        model.setRowCount(0);

        for(Patient emp : ptnDir.getPatientDirectory()){
            if(search.equals(emp.getPatiendId())){
                Object[] row = new Object[4];
                row[0] = emp;
                row[1] = emp.getName();
                row[2] = emp.getAge();
                row[3] = emp.getGender();

                model.addRow(row);
            }else{
                //                JOptionPane.showMessageDialog(this, "Invalid Data!");
            }
        }
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void AdminPatDirCityComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminPatDirCityComboActionPerformed
        // TODO add your handling code here:
        for (Map.Entry<String, ArrayList<String>> entry : map.entrySet()) {

            if (AdminPatDirCityCombo.getSelectedItem() != null) {

                if (AdminPatDirCityCombo.getSelectedItem().equals(entry.getKey())) {
                    ArrayList<String> list = entry.getValue();
                    AdminPatDirCityCombo.removeAllItems();

                    for (String community : list) {
                        AdminPatDirCityCombo.addItem(community);
                    }

                }

            }

        }
    }//GEN-LAST:event_AdminPatDirCityComboActionPerformed

    private void AdminPatDirCommComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminPatDirCommComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminPatDirCommComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AdminPatDirCityCombo;
    private javax.swing.JComboBox<String> AdminPatDirCommCombo;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JLabel AgeLabel1;
    private javax.swing.JLabel AgeLabel2;
    private javax.swing.JLabel AgeLabel3;
    private javax.swing.JLabel AgeLabel4;
    private javax.swing.JLabel AgeLabel5;
    private javax.swing.JLabel ContactLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel NameLabel1;
    private javax.swing.JLabel NewEmployeeLabel;
    private javax.swing.JLabel PersonalInfoLabel;
    private javax.swing.JLabel PersonalInfoLabel1;
    private javax.swing.JTextField SearchTxtBox;
    private javax.swing.JTable Table;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_view;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtbx_age;
    private javax.swing.JTextField txtbx_bloodgroup;
    private javax.swing.JTextField txtbx_contact;
    private javax.swing.JTextField txtbx_email;
    private javax.swing.JTextField txtbx_gender;
    private javax.swing.JTextField txtbx_height;
    private javax.swing.JTextField txtbx_id;
    private javax.swing.JTextField txtbx_name;
    private javax.swing.JTextField txtbx_weight;
    // End of variables declaration//GEN-END:variables
}
