/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Person;
import Model.PersonDirectory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vivek
 */
public class AdminPerson extends javax.swing.JPanel {

    /**
     * Creates new form AdminPerson
     */
    
    PersonDirectory prnDir;
    
    public AdminPerson(PersonDirectory prnDir) {
        initComponents();
        this.prnDir = prnDir;
        
        populateTable();
    }
 
       
    private void populateTable(){
        
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        model.setRowCount(0);
        
        for(Person prn : prnDir.getpersonDirectory()){
            
            Object[] row = new Object[4];
            row[0] = prn;
            row[1] = prn.getName();
            row[2] = prn.getAge();
            row[3] = prn.getContact();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtbx_gender = new javax.swing.JTextField();
        txtbx_age = new javax.swing.JTextField();
        GenderLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        NameLabel1 = new javax.swing.JLabel();
        txtbx_contact = new javax.swing.JTextField();
        txtbx_name = new javax.swing.JTextField();
        txtbx_id = new javax.swing.JTextField();
        btn_view = new javax.swing.JButton();
        NewEmployeeLabel = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        PersonalInfoLabel1 = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        ContactLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        PersonalInfoLabel = new javax.swing.JLabel();
        btn_update1 = new javax.swing.JButton();

        GenderLabel.setText("Gender");

        NameLabel.setText("Person ID");

        NameLabel1.setText("Name");

        btn_view.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_view.setText("View");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });

        NewEmployeeLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        NewEmployeeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewEmployeeLabel.setText("Person Directory");

        btn_update.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        PersonalInfoLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        PersonalInfoLabel1.setText("Conatct Information");

        AgeLabel.setText("Age");

        ContactLabel.setText("Contact");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Person ID", "Name", "Age", "Contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table);

        PersonalInfoLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        PersonalInfoLabel.setText("Personal Details");

        btn_update1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_update1.setText("Delete");
        btn_update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(NewEmployeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(316, 316, 316))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(GenderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(13, 13, 13))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AgeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(34, 34, 34))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(22, 22, 22)))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtbx_id)
                                    .addComponent(txtbx_gender)
                                    .addComponent(txtbx_age)
                                    .addComponent(txtbx_name)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PersonalInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(116, 116, 116))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(PersonalInfoLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(49, 49, 49))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ContactLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(150, 150, 150))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtbx_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(551, 551, 551))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(555, 555, 555)
                        .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_view, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_update1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(NewEmployeeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_view)
                .addGap(40, 40, 40)
                .addComponent(PersonalInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(txtbx_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel1)
                    .addComponent(txtbx_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel)
                    .addComponent(txtbx_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel)
                    .addComponent(txtbx_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PersonalInfoLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContactLabel)
                    .addComponent(txtbx_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_update1)
                    .addComponent(btn_update))
                .addContainerGap(258, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        // TODO add your handling code here:
//
        int row = Table.getSelectedRow();

        if(row<0){
            JOptionPane.showMessageDialog(this, "Please select a ROW to search ");
            return;
        }
//
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        Person selectedPerson = (Person)model.getValueAt(row, 0);

//
        txtbx_id.setText(selectedPerson.getPersonID());
        txtbx_name.setText(selectedPerson.getName());
      //  txtbx_email.setText(selectedPerson.getEmail());
        txtbx_contact.setText(selectedPerson.getContact());
        txtbx_gender.setText(selectedPerson.getGender());
        txtbx_age.setText(selectedPerson.getAge());
        
        
//
    }//GEN-LAST:event_btn_viewActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        boolean valid = validationForFields();
        int row = Table.getSelectedRow();

        if(row<0){
            JOptionPane.showMessageDialog(this, "Please select a ROW to search ");
            return;
        }
//
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        Person selectedPerson = (Person)model.getValueAt(row, 0);
        
        String id = txtbx_id.getText();
        String name = txtbx_name.getText();
       // String email = txtbx_email.getText();
        String contact = txtbx_contact.getText();
        String gender = txtbx_gender.getText();
        String age = txtbx_age.getText();
        
        if(valid){
            selectedPerson.setPersonID(id);
            selectedPerson.setName(name);
            selectedPerson.setContact(contact);
          //  selectedPerson.setEmail(email);
            selectedPerson.setGender(gender);
            selectedPerson.setAge(age);

            populateTable();
        }
        
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update1ActionPerformed
        // TODO add your handling code here:
        int row = Table.getSelectedRow();

        if(row<0){
            JOptionPane.showMessageDialog(this, "Please select a ROW to search ");
            return;
        }
//
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        Person selectedPerson = (Person)model.getValueAt(row, 0);
        
        prnDir.deletePerson(selectedPerson);
        
        JOptionPane.showMessageDialog(this, "Person Deleted!"); 
    }//GEN-LAST:event_btn_update1ActionPerformed

    private boolean validationForFields() {
    
    
                if(txtbx_name.getText().length()==0)
                {
                     JOptionPane.showMessageDialog(this," Name Can't be blank, please enter Person Name");
                     txtbx_name.requestFocus();
                     txtbx_name.setText("");
                     return false;
                }
                
               else{
        if(!txtbx_name.getText().matches("^[a-zA-Z]+[\\-'\\s]?[a-zA-Z ]+$"))
            {
                 JOptionPane.showMessageDialog(this," Invalid name. ");
                 txtbx_name.requestFocus();
                 txtbx_name.setText("");
                 return false;
                
                
            }
          }
                   if(txtbx_id.getText().isBlank() )
    {
        JOptionPane.showMessageDialog(this," Person ID Can't be blank, please enter Person ID ");
        txtbx_id.requestFocus();
        txtbx_id.setText("");
        return false;
    }
        else
        {
            
             if(!txtbx_id.getText().matches("^[0-9]{0,3}$"))
             {
                JOptionPane.showMessageDialog(this," Invalid Person, Note : Person ID is of 3 digit  ");
                txtbx_id.requestFocus();
                return false;
                
             }  
        }
                   
           if(txtbx_age.getText().isBlank() )
    {
        JOptionPane.showMessageDialog(this," Person Age Can't be blank, please enter Age ");
        txtbx_age.requestFocus();
        txtbx_age.setText("");
        return false;
    }
        else
        {
            
             if(!txtbx_age.getText().matches("^[0-9]{0,2}$"))
             {
                JOptionPane.showMessageDialog(this," Employee should be between 0 to 100 years old. ");
                txtbx_age.requestFocus();
                return false;
                
             }  
        }
                    
//           if(txtCity.getText().isBlank())
//            {
//                    JOptionPane.showMessageDialog(this," Please enter a City ");
//                    txtCity.requestFocus();
//                    //comboCity.setText("");
//                   return false;
//            }
//           
//                if(txtCommunity.getText().isBlank())
//            {
//                    JOptionPane.showMessageDialog(this," Please select a Community ");
//                    txtCommunity.requestFocus();
//                    //comboCity.setText("");
//                   return false;
//            }
                 if(txtbx_gender.getText().isBlank())
            {
                    JOptionPane.showMessageDialog(this," Please select a Gender ");
                    txtbx_gender.requestFocus();
                    //comboCity.setText("");
                   return false;
            }
            
                return true;
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JLabel ContactLabel;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel NameLabel1;
    private javax.swing.JLabel NewEmployeeLabel;
    private javax.swing.JLabel PersonalInfoLabel;
    private javax.swing.JLabel PersonalInfoLabel1;
    private javax.swing.JTable Table;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_update1;
    private javax.swing.JButton btn_view;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtbx_age;
    private javax.swing.JTextField txtbx_contact;
    private javax.swing.JTextField txtbx_gender;
    private javax.swing.JTextField txtbx_id;
    private javax.swing.JTextField txtbx_name;
    // End of variables declaration//GEN-END:variables
}
